loginPage:
  - button:
      name: products
      locator-Type: css
      locator-Value: div.inventory_item
      wait-For-Loaded: true
  - text:
      name: title item
      locator-Type: css
      locator-Value: div.inventory_item
      wait-For-Loaded: true
  - link:
      name: add to cart
      locator-Type: css
      locator-Value: button.btn
      wait-For-Loaded: true
  - link:
      name: cart icon
      locator-Type: css
      locator-Value: "#shopping_cart_container > a"
      wait-For-Loaded: true